// src/filter/any-exception.filter.ts
/**
 * 捕获所有异常
 */
import { ArgumentsHost, Catch, ExceptionFilter, HttpException, HttpStatus } from "@nestjs/common";
import { Logger } from "../../utils/log4js";

@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();

    const status =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;

    const logFormat = `<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      Request original url: ${request.originalUrl}
      Method: ${request.method}
      IP: ${request.ip}
      Status code: ${status}
      Response: ${exception} \n  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    `;
    Logger.error(logFormat);

    /**
     * 封装的统一业务请求错误返回体
     *
     * code: 为自定义的业务错误返回码
     * success: 默认为 true, 在service中可以在业务发生错误的场景中传 false
     * data: 在没有传值的情况下，默认为 null
     * message: 只要没有抛出HTTP错误，message 就是自己定义的，默认为 success
     */

    console.log("====base=====");
    response.status(status).send({
      code: status,
      success: false,
      data: null,
      message: (exception as any).message
    });
  }
}
